### ISSUE TITLE
Why no releases?

### ISSUE THREAD

**Issue by punitganshani** [ms-iot/forwarders#6]
We have to manually build the project in Release mode (although not time consuming), and then copy the user32.dll to IoT device.

If nodeJs developers want to use this on IoT devices running on Windows, they should not require Visual Studio to build this library.

Can we have releases of this project so that we just need to download the required DLLs instead of building them in VS?

**Comment by ooeygui** [comment]
Hi there,
We could have just made some changes to our implementation of User32.dll but then you would have been left with the possible problem of making native extensions work. As Node changes and as native modules proliferate, the forwarders project would need to adapt. By building it, you will always have the latest support.

We would very much appreciate contributions to help support more native extensions.

As the forwarders project matures, we'd like to make this part of the Windows release.

**Comment by punitganshani** [comment]
Thanks appreciate it.  But do we have some *good* documentation on getting this running on Galileo?

**Comment by ooeygui** [comment]
Sorry for the delay in responding. We haven't had a process for binary releases through Nuget. We will be working on the details.
With the release of Windows 10 Core, Node.js is integrated into the build. If you have a Raspberry Pi, I encourage you to take a peek at: http://ms-iot.github.io/content/win10/samples/NodejsWUBlinky.htm.

**Comment by ooeygui** [comment]
We have put on hold new feature development on the Galileo. See our FAQ. Node.js is supported on Windows 10. http://ms-iot.github.io/content/Faqs.htm#galileo
